import arabian from './images/Horses/arabian.jpeg'
import arabian1 from './images/Horses/arabian1.jpeg'
import arabian2 from './images/Horses/arabian2.jpeg'
import morgan from './images/Horses/morgan.jpeg'
import thoroughbred from './images/Horses/thoroughbred.jpeg'
import quarterhorse from './images/Horses/quarterhorse.jpeg'
import appaloosa from './images/Horses/appaloosa.jpeg'
import clydesdale from './images/Horses/clydesdale.jpeg'
import shire from './images/Horses/shire.jpeg'
import percheron from  './images/Horses/percheron.jpeg'
import belgian from './images/Horses/belgian.jpeg'
import shetland from './images/Horses/shetland.jpeg'
import welsh from  './images/Horses/welsh.jpeg'
import fell from './images/Horses/fell.jpeg'
import icelandic from './images/Horses/icelandic.jpeg'
import pasofino from './images/Horses/pasofino.jpeg'
import dutchwarmblood from './images/Horses/dutchwarmblood.jpeg'
import hanoverian from './images/Horses/hanoverian.jpeg'
import trakehner from './images/Horses/trakehner.jpeg'
import friesian from './images/Horses/friesian.jpeg'
import gypsyvanner from './images/Horses/gypsyvanner.jpeg'
import andalusian from './images/Horses/andalusian.jpeg'
import lipizzaner from './images/Horses/lipizzaner.jpeg'
import haflinger from './images/Horses/haflinger.jpeg'

export const horsedata = [
    {
    id: 1,
    name: 'Arabian Horse',
    description: 'Originating from the Arabian Peninsula, known for their endurance and distinctive head shape.',
    img: arabian,
    breed: 'Arabian',
    price: 15000,
    age: 4,
    dob: 'November 23, 2020',
    purchaseoption: 'Buy or Lease'
    },
    {
    id: 2,
    name: 'Arabian Horse',
    description: 'Originating from the Arabian Peninsula, known for their endurance and distinctive head shape.',
    img: arabian1,
    breed: 'Arabian',
    price: 25000,
    age: 2,
    dob: 'September 19, 2022',
    purchaseoption: 'Buy'
    },
    {
    id: 3,
    name: 'Arabian Horse',
    description: 'Originating from the Arabian Peninsula, known for their endurance and distinctive head shape.',
    img: arabian2,
    breed: 'Arabian',
    price: 12000,
    age: 5,
    dob: 'July 2, 2019',
    purchaseoption: 'Lease'
    },
    {
    id: 4,
    name: 'Morgan Horse',
    description: 'An American breed known for its strength and versatility.',
    img: morgan,
    breed: 'Morgan',
    price: 9000,
    age: 1,
    dob: 'July 2, 2023',
    purchaseoption: 'Buy',
    },
    {
    id: 5,
    name: 'Thoroughbred Horse',
    description: 'Known for their speed and agility, often used in racing.',
    img: thoroughbred,
    breed: 'Thoroughbred',
    price: 30000,
    age: 3,
    dob: 'March 15, 2021',
    purchaseoption: 'Buy or Lease',
    },
    {
    id: 6,
    name: 'Quarter Horse',
    description: 'Renowned for their speed over short distances and versatility.',
    img: quarterhorse,
    breed: 'Quarter Horse',
    price: 18000,
    age: 4,
    dob: 'May 22, 2020',
    purchaseoption: 'Buy',
  },
  {
    id: 7,
    name: 'Appaloosa Horse',
    description: 'Recognizable for their colorful spotted coat patterns.',
    img: appaloosa,
    breed: 'Appaloosa',
    price: 14000,
    age: 3,
    dob: 'June 11, 2021',
    purchaseoption: 'Buy or Lease',
  },
  {
    id: 8,
    name: 'Clydesdale Horse',
    description: 'Known for their large size and distinctive feathering on their lower legs.',
    img: clydesdale,
    breed: 'Clydesdale',
    price: 22000,
    age: 5,
    dob: 'August 3, 2019',
    purchaseoption: 'Lease',
  },
  {
    id: 9,
    name: 'Shire Horse',
    description: 'One of the largest horse breeds, known for their strength and gentle nature.',
    img: shire,
    breed: 'Shire',
    price: 25000,
    age: 6,
    dob: 'April 27, 2018',
    purchaseoption: 'Buy',
  },
  {
    id: 10,
    name: 'Percheron Horse',
    description: 'Known for their strength and versatility, often used in draft work.',
    img: percheron,
    breed: 'Percheron',
    price: 17000,
    age: 4,
    dob: 'December 14, 2019',
    purchaseoption: 'Buy or Lease',
  },
  {
    id: 11,
    name: 'Belgian Horse',
    description: 'Known for their strength and gentle temperament, commonly used for heavy farm work.',
    img: belgian,
    breed: 'Belgian',
    price: 19000,
    age: 5,
    dob: 'September 8, 2018',
    purchaseoption: 'Lease',
  },
  {
    id: 12,
    name: 'Shetland Pony',
    description: 'Small, sturdy ponies known for their hardiness and often used as children\'s riding ponies.',
    img: shetland,
    breed: 'Shetland Pony',
    price: 8000,
    age: 2,
    dob: 'January 17, 2022',
    purchaseoption: 'Buy',
  },
  {
    id: 13,
    name: 'Welsh Pony',
    description: 'Versatile ponies known for their good temperament.',
    img: welsh,
    breed: 'Welsh Pony',
    price: 9000,
    age: 3,
    dob: 'February 28, 2021',
    purchaseoption: 'Buy or Lease',
  },
  {
    id: 14,
    name: 'Fell Pony',
    description: 'Known for their hardiness and versatility, often used for riding and driving.',
    img: fell,
    breed: 'Fell Pony',
    price: 10000,
    age: 4,
    dob: 'October 5, 2020',
    purchaseoption: 'Buy',
  },
  {
    id: 15,
    name: 'Icelandic Horse',
    description: 'Known for their unique gaits, the tölt and flying pace.',
    img: icelandic,
    breed: 'Icelandic Horse',
    price: 15000,
    age: 3,
    dob: 'November 12, 2021',
    purchaseoption: 'Buy or Lease',
  },
  {
    id: 16,
    name: 'Paso Fino Horse',
    description: 'Known for their smooth gait and often used in trail riding.',
    img: pasofino,
    breed: 'Paso Fino',
    price: 16000,
    age: 4,
    dob: 'July 29, 2020',
    purchaseoption: 'Buy',
  },
  {
    id: 17,
    name: 'Dutch Warmblood Horse',
    description: 'Known for their excellence in dressage and show jumping.',
    img: dutchwarmblood,
    breed: 'Dutch Warmblood',
    price: 35000,
    age: 6,
    dob: 'June 16, 2018',
    purchaseoption: 'Buy or Lease',
  },
  {
    id: 18,
    name: 'Hanoverian Horse',
    description: 'Renowned for their athleticism and temperament.',
    img: hanoverian,
    breed: 'Hanoverian',
    price: 32000,
    age: 5,
    dob: 'August 24, 2019',
    purchaseoption: 'Lease',
  },
  {
    id: 19,
    name: 'Trakehner Horse',
    description: 'Known for their agility, strength, and good temperament.',
    img: trakehner,
    breed: 'Trakehner',
    price: 31000,
    age: 4,
    dob: 'September 30, 2020',
    purchaseoption: 'Buy',
  },
  {
    id: 20,
    name: 'Friesian Horse',
    description: 'Recognizable by their black coat and high-stepping trot.',
    img: friesian,
    breed: 'Friesian',
    price: 28000,
    age: 6,
    dob: 'April 19, 2018',
    purchaseoption: 'Buy or Lease',
  },
  {
    id: 21,
    name: 'Gypsy Vanner Horse',
    description: 'Known for their distinctive feathering and colorful coats.',
    img: gypsyvanner,
    breed: 'Gypsy Vanner',
    price: 26000,
    age: 5,
    dob: 'May 25, 2019',
    purchaseoption: 'Buy',
  },
  {
    id: 22,
    name: 'Andalusian Horse',
    description: 'Known for their elegance and used in classical dressage.',
    img: andalusian,
    breed: 'Andalusian',
    price: 34000,
    age: 4,
    dob: 'July 10, 2020',
    purchaseoption: 'Buy or Lease',
  },
  {
    id: 23,
    name: 'Lipizzaner Horse',
    description: 'Known for their use in classical dressage, originating from Spain.',
    img: lipizzaner,
    breed: 'Lipizzaner',
    price: 36000,
    age: 5,
    dob: 'March 22, 2019',
    purchaseoption: 'Lease',
  },
  {
    id: 24,
    name: 'Haflinger Horse',
    description: 'Known for its chestnut color and versatility, used in riding and driving.',
    img: haflinger,
    breed: 'Haflinger',
    price: 12000,
    age: 3,
    dob: 'April 14, 2021',
    purchaseoption: 'Buy',
  }
]